Mk1
kobiez/Chat-App pull request #1
Opened 2022-01-05 17:07 UTC by kobiez

I added tests file to auth directory, frequently I don't think it was needed, but I kept it so I can practice.
I tried to find other tests to execute but lack any ideas, so if you have any, list them for me and I add them to the code.

2022-01-05 20:22 UTC, matan-co requested changes
Good job :) 
Added some comments

2022-01-05 20:22 UTC, matan-co commented on README.txt
> +Hi
Please follow this website how to write readmes https://www.makeareadme.com/

2022-01-05 20:22 UTC, matan-co commented on server/api/v1/auth/auth.test.js
> +    const noUserId = await request.post("/api/v1/index").expect(404);
dont use 404 use http status package instead

2022-01-05 20:22 UTC, matan-co commented on server/api/v1/auth/auth.test.js
> +    const noUserId = await request.post("/api/v1/index").expect(404);
This test does not make sense. you are doing POST call to a not defined route. 
Please create a test that checks this. Happy flow. create use and get one. and check it.

2022-01-05 20:22 UTC, matan-co commented on server/api/v1/auth/auth.test.js
> +    const noUserId = await request.post("/api/v1/index").expect(404);
If you want to implement getUserID method it should be with HTTP GET instead but you should implement this function.

2022-01-06 09:07 UTC, kobiez commented on README.txt
> +Hi
Thanks for your comment,
I edited the readme file. of course it's not finished yet, but I think that I understand the concept.

2022-01-06 09:10 UTC, kobiez commented on server/api/v1/auth/auth.test.js
> +    const noUserId = await request.post("/api/v1/index").expect(404);
FIxed it.

2022-01-06 15:23 UTC, kobiez commented on server/api/v1/auth/auth.test.js
> +    const noUserId = await request.post("/api/v1/index").expect(404);
Fixed what you asked for in the first comment.
About getUserID method, already checked it with the first test in auth directory.

2022-01-06 19:43 UTC, matan-co commented on README.md
> +<p>As the title suggests, it's a chat platform, but in order to use it you first need to log into it and just then you will be able to chat with other person</p>
Please take a look here https://www.makeareadme.com/#template-1
It more used to write sections with "#"

2022-01-06 19:43 UTC, matan-co commented on server/api/v1/auth/auth.test.js
> +it("Check if there is userId", async () => {
Instead of "Check if there is userId" better name for tests start with should bla bla bla 
In this case "POST Auth - should create a new user id "

2022-01-06 19:43 UTC, matan-co commented on server/api/v1/auth/auth.test.js
> +it("Return NOT FOUND status if route not defined", async () => {
same here "should return ..."

2022-01-06 19:43 UTC, matan-co commented on server/api/v1/message/message.test.js
>      .post("/api/v1/message")
Instead of copy pase "/api/v1/message" a lot of time. Put it in variable baseUrl

2022-01-06 22:08 UTC, kobiez commented on server/api/v1/auth/auth.test.js
> +it("Check if there is userId", async () => {
Fixed

2022-01-06 22:09 UTC, kobiez commented on server/api/v1/auth/auth.test.js
> +it("Return NOT FOUND status if route not defined", async () => {
Fixed

2022-01-06 22:10 UTC, kobiez commented on server/api/v1/message/message.test.js
>      .post("/api/v1/message")
Done

2022-01-07 07:44 UTC, matan-co commented on README.md
> +<p>As the title suggests, it's a chat platform, but in order to use it you first need to log into it and just then you will be able to chat with other person</p>
![image](https://user-images.githubusercontent.com/33671703/148509645-af433d0d-286d-4337-aea1-41520ea2db78.png)

2022-01-07 11:09 UTC, kobiez commented on README.md
> +<p>As the title suggests, it's a chat platform, but in order to use it you first need to log into it and just then you will be able to chat with other person</p>
Fixed it

2022-01-07 14:03 UTC, matan-co approved these changes
Great job :)

2022-01-08 16:11 UTC, merged