Chat logic
kobiez/Chat-App pull request #2
Opened 2022-01-09 19:07 UTC by kobiez

Configure the message.js to return the messages as a string.
I want to delete line 16 from the code, I think that we need to show the messages only in the GET request.

2022-01-09 19:11 UTC, matan-co requested changes
Ill add more comments later

2022-01-09 19:11 UTC, matan-co commented on README.md
> +### How To use
In most of the systems you should tell something like
npm install
npm start.

And it should be with ``` section. Please take a look in the link that i sent you before.

2022-01-11 20:50 UTC, matan-co requested changes
Nice job 😁👌
Added some comments

2022-01-11 20:50 UTC, matan-co commented on client/public/index.html
> +        }
move this logic to css file

2022-01-11 20:50 UTC, matan-co commented on client/public/index.js
> +} */
remove this code if not needed

2022-01-11 20:50 UTC, matan-co commented on client/public/index.js
> +async function generateID() {
Break this file into 2 files. authService and messageService. like we did in the server we are doing it in the client. 
Create a directory that call services. and put the logic of the api calls in there.

2022-01-11 20:50 UTC, matan-co commented on server/api/v1/auth/auth.test.js
> +    const UserId = await request.post("/api/v1/auth").expect(httpStatus.OK);
UserId should be camel case.

2022-01-11 20:50 UTC, matan-co commented on server/api/v1/auth/auth.test.js
> +    console.log(UserId.body);
remove unneeded console.log

2022-01-11 20:50 UTC, matan-co commented on server/api/v1/message/message.js
> +  const message = req.body.message;
Please read on javascript destruction . 
https://dmitripavlutin.com/javascript-object-destructuring/

2022-01-11 20:50 UTC, matan-co commented on server/api/v1/message/message.js
> +  const message = req.body.message;
![image](https://user-images.githubusercontent.com/33671703/149019293-f6067ef7-ff3a-493c-8fc6-f888ddbd7cb9.png)

2022-01-11 20:50 UTC, matan-co commented on server/api/v1/message/message.js
> +  const message = req.body.message;
you can do const {message} = req.body;

2022-01-12 10:31 UTC, kobiez commented on client/public/index.js
> +async function generateID() {
I ran into an issue when trying to split as you asked, I wasn't able to export the userId variable from authService file to messageService file.

2022-01-12 10:31 UTC, kobiez commented on client/public/index.html
> +        }
Moved it

2022-01-12 10:31 UTC, kobiez commented on client/public/index.js
> +} */
Done

2022-01-12 10:32 UTC, kobiez commented on server/api/v1/auth/auth.test.js
> +    const UserId = await request.post("/api/v1/auth").expect(httpStatus.OK);
Done

2022-01-12 10:33 UTC, kobiez commented on server/api/v1/auth/auth.test.js
> +    console.log(UserId.body);
Done

2022-01-12 11:06 UTC, kobiez commented on server/api/v1/message/message.js
> +  const message = req.body.message;
Fixed it. 
Read it.

2022-01-13 05:40 UTC, matan-co approved these changes

2022-01-13 10:05 UTC, merged